# Generated by Django 5.2.3 on 2025-06-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='percent_correct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='quiz_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
