# Generated by Django 5.2.3 on 2025-07-04 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_remove_quizattempt_percent_correct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='percent_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='quiz_hash',
            field=models.CharField(default='', max_length=64),
        ),
    ]
